### ISSUE TITLE
How did you decompile this?

### ISSUE THREAD

**Issue by dky4** [Puyodead1/HeistProject#1]
Uh, i know this is old but how did you decompile the  mod?

**Comment by Puyodead1** [comment]
> Uh, i know this is old but how did you decompile the mod?

why?

**Comment by dky4** [comment]
i'm trying to decompile a different mod and was wondering if anyone knew how to

**Comment by Puyodead1** [comment]
> i'm trying to decompile a different mod and was wondering if anyone knew how to

C# is really easy to decompile. just get a dotnet decompiler
