### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by PoplajZ** [Puyodead1/HeistProject#2]
I put everything from main file to scripts and it doesnt work.

**Comment by Puyodead1** [comment]
> I put everything from main file to scripts and it doesnt work.

wdym "doesnt work"

**Comment by PoplajZ** [comment]
Well, it just didn't loaded the program, got stucked

**Comment by Puyodead1** [comment]
> Well, it just didn't loaded the program, got stucked

doesnt really tell me anything useful, i just tested it and it works fine so you must not have installed it correctly or something. Either way, I recommend using Build A Mission instead
