### ISSUE TITLE
Does it work with rage co-op mod?

### ISSUE THREAD

**Issue by CiroBurro** [Puyodead1/HeistProject#3]
Can i play those heists with a friend using rage coop mod or are they only for one player?

**Comment by CiroBurro** [comment]
And eventually, how can we play a mission toghether?

**Comment by JimmisAtha** [comment]
I do have the same question, can we remove bots & invite Lan session players??? GTA Online Heists don;t work btw...

**Comment by Puyodead1** [comment]
Honestly probably better to use something like Build A Mission instead, this is old and severely lacking, and i don't plan to maintain it, I just fixed an issue that prevented anyone from actually using it at all.
